version: 2.1

orbs:
  docker:
    commands:
      login:
        description: "Login to DockerHub"
        steps:
          - run:
              name: "Login to DockerHub"
              command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources

  build-and-publish-docker-images:
    docker:
      - image: circleci/buildpack-deps:stretch
    parameters:
      images_path:
        type: string
        default: ./images
      docker_username:
        type: string
        default: bartsmykla
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/login
      - run:
          name: "Build and Publish Docker Images from << parameters.images_path >>"
          command: |
            ./scripts/build_and_push.sh \
              --images-path << parameters.images_path >> \
              --docker-username << parameters.docker_username >>

workflows:
  "Build and Publish Docker Images":
    jobs:
      - shellcheck
      - build-and-publish-docker-images:
          requires:
            - shellcheck